import { SearchItem } from '@/typings';

export const data: SearchItem[] = [
    { title: 'Project Overview', path: '/docs/overview', content: 'This is the project overview content...' },
    { title: 'Technology Stack', path: '/docs/technology-stack', content: 'Details about the technology stack...' },
    { title: 'Architecture and System Design', path: '/docs/architecture-and-system-design', content: 'Description of the architecture and system design...' },
    { title: 'User Interface and User Experience', path: '/docs/user-interface', content: 'Information about the user interface and user experience...' },
    { title: 'Development Workflow and Processes', path: '/docs/development-workflow-and-processes', content: 'Overview of development workflow and processes...' },
    { title: 'Performance and Scalability', path: '/docs/performance-and-scalability', content: 'Details on performance and scalability...' },
    { title: 'Security and Data Privacy', path: '/docs/security-and-data-privacy', content: 'Information on security and data privacy...' },
    { title: 'Deployment and Infrastructure', path: '/docs/deployment-infrastructure', content: 'Description of deployment and infrastructure...' },
    { title: 'Third-Party Integrations', path: '/docs/third-party-integrations', content: 'Details about third-party integrations...' },
    { title: 'Brief description of the project and its objectives', path: '/docs/overview#description', content: 'Brief description of the project and its objectives...' },
    { title: 'Key features and functionalities', path: '/docs/overview#features', content: 'Key features and functionalities of the project...' },
    { title: 'Target audience and user personas', path: '/docs/overview#target-audience', content: 'Target audience and user personas for the project...' },
    { title: 'Frontend', path: '/docs/technology-stack#frontend', content: 'Frontend technologies including Next.js, Tailwind CSS, Daisy UI, and Framer Motion...' },
    { title: 'Backend', path: '/docs/technology-stack#backend', content: 'Backend technologies including Next.js API routes or a separate backend if necessary...' },
    { title: 'Database', path: '/docs/technology-stack#database', content: 'Database technologies including MongoDB...' },
    { title: 'Other dependencies and libraries', path: '/docs/technology-stack#dependencies', content: 'Other dependencies and libraries used in the project...' },
    { title: 'High-level system architecture diagram', path: '/docs/architecture-and-system-design#high-level-architecture', content: 'High-level system architecture diagram...' },
    { title: 'Client-side architecture', path: '/docs/architecture-and-system-design#client-side', content: 'Client-side architecture including React components, state management, routing...' },
    { title: 'Server-side architecture', path: '/docs/architecture-and-system-design#server-side', content: 'Server-side architecture including API routes, data fetching, caching...' },
    { title: 'Database design', path: '/docs/architecture-and-system-design#database-design', content: 'Database design including schema, data modeling, indexing...' },
    { title: 'Authentication and authorization strategies', path: '/docs/architecture-and-system-design#auth-strategies', content: 'Authentication and authorization strategies...' },
    { title: 'Payment integration', path: '/docs/architecture-and-system-design#payment-integration', content: 'Payment integration using Stripe, PayPal...' },
    { title: 'Order tracking and shipping integration', path: '/docs/architecture-and-system-design#order-tracking', content: 'Order tracking and shipping integration using third-party APIs...' },
    { title: 'Wireframes and mockups for key pages and components', path: '/docs/user-interface#wireframes', content: 'Wireframes and mockups for key pages and components...' },
    { title: 'UI component library and design system', path: '/docs/user-interface#ui-library', content: 'UI component library and design system using Tailwind CSS and Daisy UI...' },
    { title: 'Responsive design and mobile considerations', path: '/docs/user-interface#responsive-design', content: 'Responsive design and mobile considerations...' },
    { title: 'Accessibility standards and best practices', path: '/docs/user-interface#accessibility', content: 'Accessibility standards and best practices...' },
    { title: 'Git branching and merging strategy', path: '/docs/development-workflow-and-processes#git-strategy', content: 'Git branching and merging strategy...' },
    { title: 'Continuous Integration and Continuous Deployment (CI/CD) setup', path: '/docs/development-workflow-and-processes#ci-cd', content: 'Continuous Integration and Continuous Deployment (CI/CD) setup...' },
    { title: 'Testing strategy', path: '/docs/development-workflow-and-processes#testing', content: 'Testing strategy including unit tests, integration tests, end-to-end tests...' },
    { title: 'Code review and quality assurance processes', path: '/docs/development-workflow-and-processes#code-review', content: 'Code review and quality assurance processes...' },
    { title: 'Agile project management', path: '/docs/development-workflow-and-processes#agile', content: 'Agile project management including sprints, task tracking, retrospectives...' },
    { title: 'Server-side rendering (SSR) and static site generation (SSG) strategies', path: '/docs/performance-and-scalability#ssr-ssg', content: 'Server-side rendering (SSR) and static site generation (SSG) strategies...' },
    { title: 'Caching mechanisms', path: '/docs/performance-and-scalability#caching', content: 'Caching mechanisms including client-side, server-side, CDN...' },
    { title: 'Load balancing and horizontal scaling considerations', path: '/docs/performance-and-scalability#load-balancing', content: 'Load balancing and horizontal scaling considerations...' },
    { title: 'Performance optimization techniques', path: '/docs/performance-and-scalability#optimization', content: 'Performance optimization techniques including code splitting, lazy loading, image optimization...' },
    { title: 'HTTPS and SSL/TLS implementation', path: '/docs/security-and-data-privacy#https', content: 'HTTPS and SSL/TLS implementation...' },
    { title: 'Cross-Site Scripting (XSS) and Cross-Site Request Forgery (CSRF) protection', path: '/docs/security-and-data-privacy#xss-csrf', content: 'Cross-Site Scripting (XSS) and Cross-Site Request Forgery (CSRF) protection...' },
    { title: 'Input validation and sanitization', path: '/docs/security-and-data-privacy#input-validation', content: 'Input validation and sanitization...' },
    { title: 'Data encryption and secure storage', path: '/docs/security-and-data-privacy#data-encryption', content: 'Data encryption and secure storage...' },
    { title: 'Compliance with relevant data privacy regulations', path: '/docs/security-and-data-privacy#compliance', content: 'Compliance with relevant data privacy regulations including GDPR, CCPA...' },
    { title: 'Hosting and deployment options', path: '/docs/deployment-infrastructure#hosting', content: 'Hosting and deployment options including Vercel, AWS, Google Cloud...' },
    { title: 'Serverless functions and serverless architecture considerations', path: '/docs/deployment-infrastructure#serverless', content: 'Serverless functions and serverless architecture considerations...' },
    { title: 'Content Delivery Network (CDN) and edge computing', path: '/docs/deployment-infrastructure#cdn-edge', content: 'Content Delivery Network (CDN) and edge computing...' },
    { title: 'Monitoring and logging strategies', path: '/docs/deployment-infrastructure#monitoring', content: 'Monitoring and logging strategies...' },
    { title: 'Blog platform integration', path: '/docs/third-party-integrations#blog', content: 'Blog platform integration including Contentful, Sanity.io...' },
    { title: 'Analytics and tracking', path: '/docs/third-party-integrations#analytics', content: 'Analytics and tracking including Google Analytics, Mixpanel...' },
    { title: 'Social media sharing and authentication', path: '/docs/third-party-integrations#social-media', content: 'Social media sharing and authentication...' },
  ];
  